/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Counter: (() => {
      const tableId = new TableId("", "Counter");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Card: (() => {
      const tableId = new TableId("", "Card");
      return defineComponent(
        world,
        {
          attack: RecsType.Number,
          health: RecsType.Number,
          cost: RecsType.Number,
          ability_type: RecsType.Number,
          ability_value: RecsType.Number,
          creator: RecsType.String,
          exists: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Board: (() => {
      const tableId = new TableId("", "Board");
      return defineComponent(
        world,
        {
          card: RecsType.String,
          attack: RecsType.Number,
          health: RecsType.Number,
          lastAttacked: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Game: (() => {
      const tableId = new TableId("", "Game");
      return defineComponent(
        world,
        {
          player1: RecsType.String,
          player2: RecsType.String,
          round: RecsType.Number,
          turn: RecsType.Number,
          started: RecsType.Boolean,
          start_time: RecsType.BigInt,
          last_move_time: RecsType.BigInt,
          winner: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Player: (() => {
      const tableId = new TableId("", "Player");
      return defineComponent(
        world,
        {
          health: RecsType.Number,
          mana: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
