export const lucky: string[] = [
  "The Matrix",
  "The Lord of the Rings",
  "The Hobbit",
  "The Godfather",
  "Star Wars",
  "Pulp Fiction",
  "The Dark Knight",
  "Fight Club",
  "Forrest Gump",
  "Inception",
  "Magic the Gathering",
  "Dungeons and Dragons",
  "The Witcher",
  "The Elder Scrolls",
  "The Legend of Zelda",
  "Super Mario Bros",
  "Pokemon",
  "The Legend of Korra",
  "Avatar: The Last Airbender",
  "The Simpsons",
  "Rick and Morty",
  "South Park",
  "Spongebob Squarepants",
  "The Office",
  "Friends",
  "Seinfeld",
  "Game of Thrones",
  "Breaking Bad",
  "The Walking Dead",
  "Stranger Things",
  "The Big Bang Theory",
  "The Mandalorian",
  "The Avengers",
  "Harry Potter",
  "The Hunger Games",
  "The Chronicles of Narnia",
  "The Twilight Saga",
  "The Fault in Our Stars",
  "The Great Gatsby",
  "The Da Vinci Code",
]