// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Card, CardData, CardTableId } from "./tables/Card.sol";
import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
