// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum AbilityType {
  HEAL,
  AREA_ATTACK,
  INSPIRE,
  WEAKEN
}

enum Slot {
  SLOT_1,
  SLOT_2,
  SLOT_3,
  SLOT_4,
  SLOT_5
}
