// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAttackSystem {
  function summonCard(string memory cardName, uint8 boardId) external;

  function attackCard(uint8 boardId, address targetPlayer, uint8 targetBoardId) external;

  function attackPlayer(uint8 boardId, address targetPlayer) external;
}
