// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAttackSystem {
  function summonCard(string memory cardName, uint8 boardId) external;

  function attackCard(string memory _attackingCard, string memory _targetCard) external;

  function attackPlayer(string memory _attackingCard, address targetPlayer) external;
}
