// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { AbilityType } from "./../Types.sol";

interface ICardCreationSystem {
  function createCard(
    string memory cardName,
    uint32 attack,
    uint32 health,
    uint32 cost,
    AbilityType abilityType,
    uint32 abilityValue
  ) external;
}
