// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameSystem {
  function joinPlayer1() external;

  function joinPlayer2() external;

  function startGame() external;

  function endTurn() external;

  function forfeitOpponent() external;

  function forfeit() external;
}
